config_file: null
client: IRIS
client_debug: false
timeout: 600
event_selection: default
origin_time: '2019-02-25T18:22:30.906Z'
seconds_before_event: 20
seconds_after_event: 20
event_latitude: 62.8002
event_longitude: -149.6240
event_depth_km: 73.7
event_magnitude: 3.10
networks: AK,AT,AV,CN,II,IU,TA,US,XM,XV,DE,ZE
stations: '*'
channels: 'BH?,HH?'
locations: '*'
reference_time: '2020-04-04T01:53:18.920000Z'
seconds_before_ref: 100
seconds_after_ref: 300
phase_list: null
min_dist: 0
max_dist: 300.0
min_az: 0
max_az: 360
min_lat: null
max_lat: null
min_lon: null
max_lon: null
demean: true
detrend: true
taper_percentage: 0
rotate:
- ENZ
- RTZ
remove_response: true
output_unit: VEL
water_level: 60
pre_filt: null
scale_factor: 100.0
resample_freq: 50
remove_clipped: false
log_level: DEBUG
event_tag: 2020-04-04T015318_SOUTHERN_CALIFORNIA
