event_tag: 1988-02-15T181000_KERNVILLE_EXPLOSION
config_file: null
client: LLNL
client_debug: false
timeout: 600
taup_model: ak135
event_selection: default
origin_time: "1988-02-15T18:10:00.09"
seconds_before_event: 20
seconds_after_event: 20
event_latitude: 60.175
event_longitude: -141.187
event_depth_km: 0.
event_magnitude: 4.9
networks: '*'
stations: '*'
channels: '*'
locations: '*'
reference_time: null
seconds_before_ref: 100
seconds_after_ref: 600
phase_list: null
mindistance: 0
maxdistance: 1200.0
minazimuth: 0
maxazimuth: 360
minlatitude: null
maxlatitude: null
minlongitude: null
maxlongitude: null
demean: true
detrend: true
taper_percentage: 0.05
rotate:
remove_response: true
output_unit: VEL
water_level: 60
pre_filt: default
scale_factor: 1
resample_freq: 50
remove_clipped: false
log_level: DEBUG
