event_tag: 2015-10-18T051831_TAAN_FJORD_LANDSLIDE
config_file: null
client: IRIS
client_debug: false
timeout: 600
taup_model: ak135
use_mass_download: false
event_selection: default
origin_time: '2015-10-18T05:18:31.00'
seconds_before_event: 91
seconds_after_event: 509
event_latitude: 60.175
event_longitude: -141.187
event_depth_km: 0.0
event_magnitude: 4.9
networks: AK
stations: '*'
channels: LH?
locations: '*'
reference_time: null
seconds_before_ref: 100
seconds_after_ref: 300
phase_list:
- ttall
mindistance_km: 0
maxdistance_km: 50.0
minazimuth: 0
maxazimuth: 360
minlatitude: null
maxlatitude: null
minlongitude: null
maxlongitude: null
demean: true
detrend: true
taper_percentage: 0.05
rotate:
- ZNE
remove_response: true
output_unit: VEL
water_level: 10000
pre_filt:
- 0.004
- 0.005
- 10.0
- 15.0
scale_factor: 1
resample_freq: 50
remove_clipped: false
remove_insufficient_length: true
remove_masked_data: true
fill_data_gaps: false
gap_fraction: 1.0
log_level: DEBUG
