event_tag: 2016-01-24T103037_INISKIN
config_file: null
client: IRIS
client_debug: false
timeout: 600
taup_model: ak135
event_selection: default
origin_time: "2016-01-24T10:30:37.400"
seconds_before_event: 100
seconds_after_event: 600
event_latitude: 59.75
event_longitude: -153.27
event_depth_km: 110.7
event_magnitude: 7.1
networks: 'AV,CN,ZE,AT,TA,AK,XV,II,IU,IS'
stations: '*'
channels: 'BH?,HH?'
locations: '*'
reference_time: null
seconds_before_ref: 100
seconds_after_ref: 300
phase_list: null
mindistance: 0
maxdistance: 800.0
minazimuth: 0
maxazimuth: 360
minlatitude: null
maxlatitude: null
minlongitude: null
maxlongitude: null
demean: true
detrend: true
taper_percentage: 0
rotate:
- ZNE
- RTZ
remove_response: true
output_unit: VEL
water_level: 60
pre_filt: default
scale_factor: 1
resample_freq: 50
remove_clipped: false
log_level: DEBUG
