function [otime,lon,lat,dep,mag,eid] = read_seis_obspy(ftag)
%READ_SEIS_OBSPY read a custom text file generated by write_seis_obspy.m

filename = [ftag '_obspy.txt'];

[~,eid,~,lon,lat,dep_m,mag] = textread(filename,'%f%s%s%f%f%f%f');

dep = dep_m / 1000;

otime = eid2otime(eid);
