event_tag: 2014-08-25T161903_ICELAND
config_file: null
client: IRIS
client_debug: false
timeout: 600
taup_model: ak135
use_mass_download: false
event_selection: default
origin_time: '2014-08-25T16:19:03.000000Z'
seconds_before_event: 20
seconds_after_event: 20
event_latitude: 64.612
event_longitude: -17.472
event_depth_km: 50.0
event_magnitude: 4.6
networks: Z7
stations: RODG,DYSA,LIND,LOKT,LAUF,KALF,HELI,FAG,SVIN,K250
channels: HH?
locations: '*'
reference_time: '2014-08-25T16:19:03.000000Z'
seconds_before_ref: 60
seconds_after_ref: 360
phase_list:
- ttall
mindistance_km: 20.0
maxdistance_km: 300.0
minazimuth: 0
maxazimuth: 360
minlatitude: null
maxlatitude: null
minlongitude: null
maxlongitude: null
demean: true
detrend: true
taper_percentage: 0
rotate:
- ENZ
- RTZ
remove_response: true
output_unit: VEL
water_level: 60
pre_filt: default
scale_factor: 1
resample_freq: 50
remove_clipped: false
remove_insufficient_length: true
remove_masked_data: true
fill_data_gaps: false
gap_fraction: 1.0
log_level: DEBUG
