# PySEP Template config v0.5.0
event_tag: null
config_file: null
client: IRIS
client_debug: false
timeout: 600
taup_model: ak135
use_mass_download: false
event_selection: default
origin_time: null
seconds_before_event: 20
seconds_after_event: 20
event_latitude: null
event_longitude: null
event_depth_km: null
event_magnitude: null
networks: '*'
stations: '*'
channels: '*'
locations: '*'
reference_time: null
seconds_before_ref: 100
seconds_after_ref: 300
phase_list:
- ttall
mindistance_km: 0
maxdistance_km: 20000.0
minazimuth: 0
maxazimuth: 360
minlatitude: null
maxlatitude: null
minlongitude: null
maxlongitude: null
demean: true
detrend: true
taper_percentage: 0.0
rotate: null
remove_response: true
output_unit: VEL
water_level: 60
pre_filt: default
scale_factor: 1
resample_freq: null
remove_clipped: true
remove_insufficient_length: true
remove_masked_data: true
fill_data_gaps: false
gap_fraction: 1.0
