event_tag: 2002-03-16T213324_SOCAL
config_file: null
client: IRIS
client_debug: false
timeout: 600
taup_model: ak135
use_mass_download: false
event_selection: default
origin_time: '2002-03-16T21:33:24.076'
seconds_before_event: 20
seconds_after_event: 20
event_latitude: 33.65551
event_longitude: -119.35969
event_depth_km: 15.105
event_magnitude: 4.6
networks: AZ,CI,LB,TS,TA,NC,NN,SN,II,IU,US
stations: '*'
channels: BH?
locations: '*'
reference_time: null
seconds_before_ref: 100
seconds_after_ref: 300
phase_list:
- ttall
mindistance_km: 0
maxdistance_km: 200.0
minazimuth: 0
maxazimuth: 360
minlatitude: null
maxlatitude: null
minlongitude: null
maxlongitude: null
demean: true
detrend: true
taper_percentage: 0
rotate:
- ENZ
- RTZ
remove_response: true
output_unit: VEL
water_level: 60
pre_filt: default
scale_factor: 1
resample_freq: 50
remove_clipped: false
remove_insufficient_length: true
remove_masked_data: true
fill_data_gaps: false
gap_fraction: 1.0
log_level: DEBUG
