config_file: null
client: IRIS
client_debug: false
timeout: 600
event_selection: default
origin_time: '2009-04-07T20:12:55.351000Z'
seconds_before_event: 20
seconds_after_event: 20
event_latitude: 61.4542
event_longitude: -149.7428
event_depth_km: 33.033
event_magnitude: 4.6
networks: AK,YV,AV,AT,XZ,PN
stations: '*'
channels: BH?
locations: '*'
reference_time: '2009-04-07T20:12:55.351000Z'
seconds_before_ref: 100
seconds_after_ref: 300
phase_list: null
min_dist: 0
max_dist: 300.0
min_az: 0
max_az: 360
min_lat: null
max_lat: null
min_lon: null
max_lon: null
demean: true
detrend: true
taper_percentage: 0
rotate:
- ENZ
- RTZ
remove_response: true
output_unit: VEL
water_level: 60
pre_filt: null
scale_factor: 100.0
resample_freq: 50
remove_clipped: false
log_level: DEBUG
event_tag: 2009-04-07T201255_SOUTHERN_ALASKA
