config_file: null
client: IRIS
client_debug: false
timeout: 600
event_selection: default
origin_time: '2014-08-25T16:19:03.000000Z'
seconds_before_event: 20
seconds_after_event: 20
event_latitude: 64.612
event_longitude: -17.472
event_depth_km: 50.0
event_magnitude: 4.6
networks: Z7
stations: RODG,DYSA,LIND,LOKT,LAUF,KALF,HELI,FAG,SVIN,K250
channels: HH?
locations: '*'
reference_time: '2014-08-25T16:19:03.000000Z'
seconds_before_ref: 60
seconds_after_ref: 360
phase_list: null
min_dist: 20.0
max_dist: 300.0
min_az: 0
max_az: 360
min_lat: null
max_lat: null
min_lon: null
max_lon: null
demean: true
detrend: true
taper_percentage: 0
rotate:
- ENZ
- RTZ
remove_response: true
output_unit: VEL
water_level: 60
pre_filt: null
scale_factor: 100.0
resample_freq: 50
remove_clipped: false
log_level: DEBUG
event_tag: 2014-08-25T161903_ICELAND
